server:
  port: 8800
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_admin3?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis: # redis??
    host: 127.0.0.1 # IP
    port: 6379  # ??
    password:  # ??
    connect-timeout: 10s  # ??????
    lettuce: # lettuce redis?????
      pool: # ?????
        max-active: 8  # ???????????????????? ?? 8
        max-wait: 200s  # ??????????????????????? ?? -1
        max-idle: 8 # ??????????? ?? 8
        min-idle: 0 # ??????????? ?? 0
mybatis-plus:
  global-config:
    db-config:
      id-type: auto 
  configuration:
    map-underscore-to-camel-case: true #设置驼峰命名映射
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

weixin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wx8f8a0d4f16403e8b
  secret: 4a8a1994c6ef40af53f91f7a0cf23dd1
userImagePath: D://local_image/userAvatar/
coverImagesFilePath: D://local_image/coverImgs/
voteItemImagesFilePath: D://local_image/voteItemImages/

